% QUATERNION ROTATION MATRIX
function [Rq] = R_q(q)
% This function computes the rotation matrix of the quaternion
% variables describing the 3D rotations of 3D body.

% Input sanity check
if nargin < 1
    q = sym('q%d',[4,1],'real');
end
assert(numel(q) == 4,'The quaternion must be of format [4x1]');

% Define rotation matrix from quaternion components
Rq = [(1-2*q(3)^2-q(4)*2),...
    (2*(q(2)*q(3) + q(1)*q(4))),...
    (2*(q(2)*q(4) - q(1)*q(3)));...
    (2*(q(2)*q(3) - q(1)*q(4))),...
    (1-2*q(2)^2 - 2*q(4)^2),...
    (2*(q(3)*q(4) + q(1)*q(2)));...
    (2*(q(2)*q(4) + q(1)*q(3))),...
    (2*(q(3)*q(4) - q(1)*q(2))),...
    (1 - 2*q(2)^2 - 2*q(3)^2)];
end